samples: list.txt
platform: IonTorrent #Illumina # either Illumina or IonTorrent
adapters:
    SE: "adapters_SE.fa"
    PE: "NexteraPE-PE.fa"
flash:
    M: "300" #Maximum overlap length expected in approximately 90% of read pairs
trimmomatic:
    leading: "3"
    trailing: "3"
    slidingwindow: "4:15"
    minlen: "36"
bt2idx: "refs/Bowtie2Index/hg19"
bowtie2:
    sensitive: ""
    rg: "PL:Illumina"
mh_bedfile: "refs/mh74_excel_mh.bed"
fasta_ref: "refs/Bowtie2Index/hg19.fa"
freebayes:
    variant:
        min-alternate-count: "5"
        min-mapping-quality: "20"
        min-base-quality: "30"
        use-duplicate-reads: ""
    haps:
        min-mapping-quality: "20"
        min-base-quality: "30"
        use-duplicate-reads: ""
        min-repeat-size: "0"
        no-partial-observations: ""
        max-complex-gap: "400"
        haplotype-length: "500"
vcffilter_qual: 20
